[workspace]
resolver = "3"
members = ["calculator", "minmax"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Dylan Wright"]
rust-version = "1.97.0"

[workspace.dependencies]
clap = { version = "4.6.6", features = ["derive"] }
csv = "1.4.0"
decorum = "0.4.0"
indicatif = "0.18.6"
ndarray = "0.17.2"
num-traits = "0.2.19"
polars = { version = "0.55.2", default-features = false, features = ["lazy", "parquet", "csv"] }

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 1

[profile.release]
opt-level = "z"      # "s" optimizes for size while often cooperating better with LTO than "z"
strip = true         # Complete binary stripping
lto = "fat"          # Full Link Time Optimization
codegen-units = 1    # Maximise size reduction optimisation
panic = "abort"      # Panic aborts to completely drop stack-unwinding blocks
