[package]
name = "cncalc"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Calculate distances between all combinations of stars in a cluster."
rust-version.workspace = true

[dev-dependencies]
assert_float_eq = "1.1.3"

[dependencies]
clap.workspace = true
csv.workspace = true
decorum.workspace = true
indicatif.workspace = true
ndarray.workspace = true
polars.workspace = true
