[package]
name = "minmax"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Find minimum and maximum distances for each star in the cluster."
rust-version.workspace = true

[dependencies]
clap.workspace = true
indicatif.workspace = true
ndarray.workspace = true
num-traits.workspace = true
polars.workspace = true
